version: '2'

services:
  citeproc-doi-server:
    # env_file: .env
    # image: datacite/volpino
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/home/app/webapp/public
      - ./src:/home/app/webapp/src
      - ./lib:/home/app/webapp/lib
      # - ./config:/home/app/webapp/config
      # - ./spec:/home/app/webapp/spec
